swagger: "2.0"
info:
  description: |
    {{ description }}
  version: "{{ version }}"
  title: {{ title }}
  {% if contact %}
  contact:
    name: {{ contact }}
  {% endif %}
basePath: {{ base_path }}
schemes:
  - http
  - https
{% if definitions %}
definitions:
{{ definitions|nesteddict2yaml }}
{% endif %}
{% if security_definitions %}
securityDefinitions:
{{ security_definitions|nesteddict2yaml }}
{% endif %}
paths:
